### ISSUE TITLE
关于s3dis数据结果一点疑问

### ISSUE THREAD

**Issue by YOOOOOL** [ProgrammerSakura/Pointnet_Pointnet2_pytorch-master#1]
class beam           weight: 0.280, IoU: 0.000 
class column         weight: 0.000, IoU: 0.010 
你好，我想问训练log中这两行数据weight0 时iou0.01
weight0.280 iou0 是属于正常的吗？第一次复现不是很懂

**Comment by ProgrammerSakura** [comment]
不清楚你的具体情况，我之前没跑这个数据集，按道理来说IOU不至于这么低吧。

**Comment by YOOOOOL** [comment]
今天跑的这个数据集的感觉有点怪，你可以看下你提交的代码中pointnet_point2_pytorch_master/log/sem_seg/pointnet2_sem_seg/logs/pointnet2_sem_seg.txt中也有这两行奇怪的数据，一个weight一直是0，一个iou一直是0，感觉可能是代码哪里有问题，我刚重新下了一遍数据跑了一个epoch还是有这个奇怪的现象，应该不是数据的问题

**Comment by ProgrammerSakura** [comment]
> 今天跑的这个数据集的感觉有点怪，你可以看下你提交的代码中pointnet_point2_pytorch_master/log/sem_seg/pointnet2_sem_seg/logs/pointnet2_sem_seg.txt中也有这两行奇怪的数据，一个weight一直是0，一个iou一直是0，感觉可能是代码哪里有问题，我刚重新下了一遍数据跑了一个epoch还是有这个奇怪的现象，应该不是数据的问题

那应该是代码的问题吧，要不你试试别人的源码，我记得我这个也是fork的别人的~~
